apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: podapp1
spec:
  containers:
    - name: nginx-container-pod1
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
